apiVersion: apps/v1
kind: Deployment
metadata:
  name: hellowebapp
  namespace: aspnetcore0
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hellowebapp
  template:
    metadata:
      labels:
        app: hellowebapp
    spec:
      containers:
      - name: hellowebapp
        image: ipankajg/hellowebapp:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: hellowebapp
  namespace: aspnetcore0
spec:
  ports:
  - name: http
    port: 80
  selector:
    app: hellowebapp
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hellowebapp
  namespace: aspnetcore0
  annotations:
    cert-manager.io/cluster-issuer: selfsigned-issuer
    kubernetes.io/ingress.class: traefik
spec:
  rules:
  - host: picloud0.pg.us
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: hellowebapp
            port:
              number: 80
  tls:
  - hosts:
    - picloud0.pg.us
    secretName: hellowebapp-local-cert
